version: '3.7'

services:
  reactive-resume:
    container_name: reactive-resume
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=80
    expose:
      - '80'
    ports:
      - '80:80'
